language: python
cache: pip
python:
- 3.6
services:
- mongodb
before_script:
- sleep 15
before_install:
- openssl aes-256-cbc -K $encrypted_a0a687274364_key -iv $encrypted_a0a687274364_iv
  -in gsbot-ec2.pem.enc -out /tmp/gsbot-ec2.pem -d
- openssl aes-256-cbc -K $encrypted_a0a687274364_key -iv $encrypted_a0a687274364_iv
  -in config.ini.enc -out config.ini -d
install:
- pip install -r requirements.txt
script:
- python test.py
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 400 /tmp/gsbot-ec2.pem
  - ssh-add /tmp/gsbot-ec2.pem
  - echo $PUBLIC_SSH_KEY >> $HOME/.ssh/known_hosts
deploy:
  provider: script
  script: ssh $EC2_SSH -i /tmp/gsbot-ec2.pem 
  on:
    branch: master
